### PR TITLE
Create backend-ci.yml

### PR DESCRIPTION
**Pull request by chixcancode**
This PR creates initial YAML file for running Pytest on PR

### CODE REVIEW

**Comment by what-name** [comment]
### Couple questions:
- Will a `pull_request` GitHub Action (so this one lol) run every time the PR gets a new commit, or only when the PR is submitted for the first time?
- Will this actually run? The other action did not run from the `dev` branch ([see here](https://github.com/100DaysOfCloud/100DaysOfCloudBackend/actions)), I'm afraid this won't either. Maybe do another PR to `main`? I'm looking around how to make actions work from non-default branches. [Here's a convo about it](https://github.community/t/workflow-files-only-picked-up-from-master/16129)
- Will this check out the PR itself and not either the current `dev` or `main` branch? I don't actually know, but would like to. It is not defined in the template but [this article](https://frontside.com/blog/2020-05-26-github-actions-pull_request/) says that it should check out the PR itself so should be good, I'm not sure tho. It should check out the PR itself if it's a `pull_request` type of workflow, right?

**Comment by what-name** [comment]
These are the only available settings for Actions (from a repo with full access). No mention of branches anywhere.
Screen Shot 2020-08-03 at 23 24 23

**Comment by what-name** [comment]
GitHub Actions do work if the workflow file is on a non-default branch as well as demonstrated [here](https://github.com/100DaysOfCloud/100DaysOfCloudBackend/actions/runs/193934001). Not sure what was the problem previously, but they do work now.

**Comment by chixcancode** [comment]
> ### Couple questions:
> * Will a `pull_request` GitHub Action (so this one lol) run every time the PR gets a new commit, or only when the PR is submitted for the first time?
**Action will run only on certain status changes of the PR.  https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request.  By default it is opened, reopened, and synchronize.  When a user adds a new commit to PR, the synchronize event is raised, so it will trigger the action again.**
> * ~Will this actually run? The other action did not run from the `dev` branch ([see here](https://github.com/100DaysOfCloud/100DaysOfCloudBackend/actions)), I'm afraid this won't either. Maybe do another PR to `main`? I'm looking around how to make actions work from non-default branches. [Here's a convo about it](https://github.community/t/workflow-files-only-picked-up-from-master/16129)~
> * Will this check out the PR itself and not either the current `dev` or `main` branch? I don't actually know, but would like to. It is not defined in the template but [this article](https://frontside.com/blog/2020-05-26-github-actions-pull_request/) says that it should check out the PR itself so should be good, I'm not sure tho. It should check out the PR itself if it's a `pull_request` type of workflow, right?
** Yes it should checkout PR, but there are other options if we want.  I think for our purposes, this is more straight-forward.  If we find we want more fine-grained traceability and tracking, we can do other refs.

**Comment by what-name** [comment]
CI failed because of an error in the currently present [API Lambda] test itself on the `dev` branch probably.
It seems like adding the `sam/requirements.txt` got the CI workflow triggered but the current test files are not correct, so it works!

The output of the failed workflow:
Screen Shot 2020-08-05 at 01 13 23

The file `sam/tests/test_api/test_lambda/test_get_user_by_id/test_get_user_by_id.py` indeed is lacking the env variable `DEFAULT_REGION`. Must be fixed in #5

**Pull request merged**
