### PR TITLE
#2 API for get_user_by_id

### PR DESCRIPTION
**Pull request by syedautherabbas**
API to get user data by passing user id.

### CODE REVIEW

**Comment by syedautherabbas** [comment]
@omenking  @what-name  changes as per new naming conventions for files and dirs, templates updated tp math the updates.

**Comment by what-name** [comment]
Inconsistencies in file and folder structure, don't merge yet. `SAM` vs `sam`.
Screen Shot 2020-07-31 at 08 47 06
Screen Shot 2020-07-31 at 08 47 42
Screen Shot 2020-07-31 at 08 48 14

Writing up a complete list of changes in a bit.

**Comment by syedautherabbas** [comment]
For some reason, the naming change for dirs is not flowing over in git. On local, this is how it is 

image

**Comment by syedautherabbas** [comment]
@omenking  @what-name  redundant dirs renamed to follow snake case.

**Pull request merged**
